const data = {
  products: [
    {
      name: 'Choco Cupcake',
      slug: 'choco-cupcake',
      category: 'CupCake',
      image: '/images/choco-cupcake.jpg',
      price: 450,
      brand: 'Winky',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular cupcake',
    },
    {
      name: 'SausagePizza',
      slug: 'sausage-pizza',
      category: 'Pizza',
      image: '/images/saussage-pizza.jpg',
      price: 4500,
      brand: 'Winky',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pizza',
    },
    {
      name: 'Cheese Cake',
      slug: 'cheese-cake',
      category: 'cake',
      image: '/images/cheese-cake.jpg',
      price: 2000,
      brand: 'Winky',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'The most popular cake',
    },
    {
      name: 'Birthday Cake',
      slug: 'birthday-cake',
      category: 'BD cake',
      image: '/images/birthday-cake1.jpg',
      price: 40000,
      brand: 'Winky',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Birthday cake description',
    },
    {
      name: 'Bean Paste Bun',
      slug: 'star-bread',
      category: 'bun',
      image: '/images/star-bread.jpg',
      price: 500,
      brand: 'Winky',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Sweet Bread',
    },
    {
      name: 'Sausage Roll (Sweet/Crispy)',
      slug: 'sausage-roll',
      category: 'Roll',
      image: '/images/sausage-roll.jpg',
      price: 500,
      brand: 'Winky',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Sweet and Crispy',
    },
    {
      name: 'Coconu Heart Bun',
      slug: 'coconut-heart-bun',
      category: 'Bun',
      image: '/images/coconut-heart-bun.jpg',
      price: 400,
      brand: 'Winky',
      rating: 4.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Sweet , Coconut ',
    },
    {
      name: 'Milk Paste Bun',
      slug: 'milk-paste-bun',
      category: 'Bun',
      image: '/images/milk-paste-bun.jpg',
      price: 400,
      brand: 'Winky',
      rating: 4.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Sweet , Milk ',
    },
  ],
};

export default data;
